openapi: 3.0.0
info:
  title: Order Management API
  description: API for retrieving and filtering user orders from Firestore.
  version: 1.0.0
servers:
  - url: https://order-api-63621244483.us-central1.run.app
    description: Production server
paths:
  /date:
    get:
      summary: Retrieve the current server date and time
      description: Returns the current server date and time in various formats.
      responses:
        '200':
          description: The current server date and time.
          content:
            application/json:
              schema:
                type: object
                properties:
                  iso:
                    type: string
                    format: date-time
                  date:
                    type: string
                  time:
                    type: string
        '500':
          description: Failed to retrieve date.
components:
  schemas:
    Order:
      type: object
      properties:
        orderId:
          type: string
          example: "123"
        status:
          type: string
          enum: [creada, procesando, enviada, entregada, cancelada]
          example: creada
        totalAmount:
          type: number
          example: 10
        createdAt:
          type: string
          example: 2026-01-21 06:16
        itemCount:
          type: number
          example: 10
    Item:
      type: object
      properties:
        orderId:
          type: string
          example: "12345678"
        productId:
          type: string
          example: "a1b2c3d4e5"
        name:
          type: string
          example: "producto incre√≠ble"
        quantity:
          type: string
          example: "2"
        priceAtPurchase:
          type: string
          example: "99.99"
        image:
          type: string
          format: uri
          example: "https://picsum.photos/seed/a1b2c3d4/200"
        status:
          type: string
          enum: [creada, procesando, enviada, entregada, cancelada]
          example: "enviada"