[project]
name = "purchase-orders-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=40.4.0",
    "firebase-admin>=7.1.0",
    "flask>=3.1.2",
]
